/**
 * @file    config_items.h
 * @brief   Configuration values definition
 *
 * Generated by AFW/tools/config_items.py
 */

#ifndef __CONFIG_ITEMS_H
#define __CONFIG_ITEMS_H

#include <types.h>

/* Max length of a string stored */
#define CONFIG_STRING_MAX_LEN {{ max_str_len }}

{% for d in data %}
{%- if d.content | length != 0 -%}
/** {{ d.type }} config options */
typedef enum {
{%- for item in d.content %}
    CONFIG_{{ d.type.upper() }}_{{ item.name }},{% if item.desc %} /* {{ item.desc }} */{% endif %}
{%- endfor %}
    CONFIG_{{ d.type.upper() }}_COUNT
} config_item_{{ d.type }}_t;

/** Default values for the {{ d.type }} config items */
#define CONFIG_{{ d.type.upper() }}_DEFAULTS { {%- for item in d.content %}{{ item.default }}, {% endfor -%} }
{% endif %}
{% endfor %}

{%- if bools | length != 0 -%}
/** Bool config options */
typedef enum {
{%- for item in bools %}
    CONFIG_BOOL_{{ item.name }}, {% if item.desc %}/* {{ item.desc }} */{% endif %}
{%- endfor %}
    CONFIG_BOOL_COUNT
} config_item_bool_t;

/** Default values for the bool config items */
#define CONFIG_BOOL_DEFAULTS { {%- for val in bool_default %}{{ "0x%02x" % val }}, {%- endfor -%} }
{%- endif %}

#endif

